// MCU theatrical films in release order. `id` is the index and is permanent:
// future films must only ever be appended, never inserted or removed, or every
// shared URL in the wild breaks.
export const MOVIES = [
  { slug: 'iron-man', title: 'Iron Man', year: 2008 },
  { slug: 'the-incredible-hulk', title: 'The Incredible Hulk', year: 2008 },
  { slug: 'iron-man-2', title: 'Iron Man 2', year: 2010 },
  { slug: 'thor', title: 'Thor', year: 2011 },
  { slug: 'captain-america-the-first-avenger', title: 'Captain America: The First Avenger', year: 2011 },
  { slug: 'the-avengers', title: 'The Avengers', year: 2012 },
  { slug: 'iron-man-3', title: 'Iron Man 3', year: 2013 },
  { slug: 'thor-the-dark-world', title: 'Thor: The Dark World', year: 2013 },
  { slug: 'captain-america-the-winter-soldier', title: 'Captain America: The Winter Soldier', year: 2014 },
  { slug: 'guardians-of-the-galaxy', title: 'Guardians of the Galaxy', year: 2014 },
  { slug: 'avengers-age-of-ultron', title: 'Avengers: Age of Ultron', year: 2015 },
  { slug: 'ant-man', title: 'Ant-Man', year: 2015 },
  { slug: 'captain-america-civil-war', title: 'Captain America: Civil War', year: 2016 },
  { slug: 'doctor-strange', title: 'Doctor Strange', year: 2016 },
  { slug: 'guardians-of-the-galaxy-vol-2', title: 'Guardians of the Galaxy Vol. 2', year: 2017 },
  { slug: 'spider-man-homecoming', title: 'Spider-Man: Homecoming', year: 2017 },
  { slug: 'thor-ragnarok', title: 'Thor: Ragnarok', year: 2017 },
  { slug: 'black-panther', title: 'Black Panther', year: 2018 },
  { slug: 'avengers-infinity-war', title: 'Avengers: Infinity War', year: 2018 },
  { slug: 'ant-man-and-the-wasp', title: 'Ant-Man and the Wasp', year: 2018 },
  { slug: 'captain-marvel', title: 'Captain Marvel', year: 2019 },
  { slug: 'avengers-endgame', title: 'Avengers: Endgame', year: 2019 },
  { slug: 'spider-man-far-from-home', title: 'Spider-Man: Far From Home', year: 2019 },
  { slug: 'black-widow', title: 'Black Widow', year: 2021, logo: 'assets/logos/black-widow.svg' },
  { slug: 'shang-chi', title: 'Shang-Chi and the Legend of the Ten Rings', year: 2021 },
  { slug: 'eternals', title: 'Eternals', year: 2021 },
  { slug: 'spider-man-no-way-home', title: 'Spider-Man: No Way Home', year: 2021 },
  { slug: 'doctor-strange-multiverse-of-madness', title: 'Doctor Strange in the Multiverse of Madness', year: 2022 },
  { slug: 'thor-love-and-thunder', title: 'Thor: Love and Thunder', year: 2022 },
  { slug: 'black-panther-wakanda-forever', title: 'Black Panther: Wakanda Forever', year: 2022 },
  { slug: 'ant-man-and-the-wasp-quantumania', title: 'Ant-Man and the Wasp: Quantumania', year: 2023 },
  { slug: 'guardians-of-the-galaxy-vol-3', title: 'Guardians of the Galaxy Vol. 3', year: 2023 },
  { slug: 'the-marvels', title: 'The Marvels', year: 2023 },
  { slug: 'deadpool-and-wolverine', title: 'Deadpool & Wolverine', year: 2024 },
  { slug: 'captain-america-brave-new-world', title: 'Captain America: Brave New World', year: 2025 },
  { slug: 'thunderbolts', title: 'Thunderbolts*', year: 2025 },
  { slug: 'the-fantastic-four-first-steps', title: 'The Fantastic Four: First Steps', year: 2025 },
  { slug: 'spider-man-brand-new-day', title: 'Spider-Man: Brand New Day', year: 2026 },
].map((m, id) => ({ ...m, id, logo: m.logo ?? `assets/logos/${m.slug}.png` }));

export const CATALOG_SIZE = MOVIES.length;
